### PR TITLE
Pipeline updates

### PR DESCRIPTION
**Pull request by mivade**
* Cleanup code and improve PEP8ness
* Store all passed objects to disk and try to load from there if not in memory

### CODE REVIEW

**Comment by mivade** [comment]
Addresses #3.

**Comment by mivade** [comment]
`clear_cached_objects` is meant for debugging purposes so would only be used when reworking things (although you could just as easily manually remove the directory). The whole point of caching to disk instead of memory is that if a step somewhere in the middle fails, you don't have to re-run the entire pipeline.

The next step would be to remove all explicit `joblib.dump` calls and probably move these pickle files to the top-level workspace directory. This requires more work to make sure it doesn't break things, so I decided to not worry about potentially duplicating cached files on the first pass.

**Comment by zduey** [comment]
My only concern with not clearing the cached objects is that if something about the pipeline is changed and you re-run, it could use the old files if something is wrong with the in-memory passing, which could cause a hard to find bug in the final output. Would it make sense to clear the cached objects by default if the pipeline completes without failure? This would avoid any potential for using an old object in a new run and still allow you to pick up where you left off if a crash happens midway through.

**Comment by mivade** [comment]
That's a good point. I'll make the default behavior that it removes the cache upon successful completion and add an option to keep it around (which would be useful for inspecting things after success, which was my motivation for implementing this today).

**Pull request merged**
