### PR TITLE
Hierarchical mixed model

### PR DESCRIPTION
**Pull request by zduey**
This are the updates to put the hierarchical models into production. My testing consisted of building a few fr5 reports on my local set up. For the most part, this is new code. The one thing to note is that I updated EventPreparation.py to create the reports folder earlier in the pipeline. This was because I wanted to create the plots at the time of model fitting rather than during the rest of the plot creation. The reason for doing this is that I was not able to get the model plots to behave well with the PlotUtils utilities because they set a bunch of pyplot state that don't play well with the plotting utilities built into pymc3.

### CODE REVIEW

**Comment by zduey** [comment]
@mivade Updated module names to be more pep8 compliant

**Comment by zduey** [comment]
@leondavis1 @maciekswat: Any objection to merging this request?

**Comment by mivade** [comment]
Did this ever get pulled in somehow without being merged?

**Comment by zduey** [comment]
I don't believe so. I'm working on incorporating it into the PR that will accompany the FR6 report.

**Comment by mivade** [comment]
Should we close this then?

**Comment by zduey** [comment]
Yeah, thats fine. I was only leaving it open as a reminder to myself not to forget to incorporate it

**Comment by zduey** [comment]
Closing this. These changes were inadvertently absorbed already, so no need for this PR

**Pull request closed without merging**
